export const styles = {
    chatWidget: {
        backgroundColor: 'rgb(129 140 248)',
        borderRadius: '10px',
        width: '150px',
        padding: '10px 0',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        cursor: 'pointer',
        position: 'fixed',
        bottom: '20px',
        right: '20px',
    },
    chatWidgetText: {
        marginLeft: '10px',
        color: 'white',
        fontWeight: 'bold',
    },
    modalWindow: {
        position: 'fixed',
        width: '400px',
        bottom: '20px',
        right: '20px',
        backgroundColor: 'white',
        padding: '20px',
        borderRadius: '10px',
        boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
        transition: 'opacity 0.3s ease-in-out',
    },
};
